### ISSUE TITLE
Class not found when unmarshalling: com.claudiodegio.msv.BaseMaterialSearchView$BaseMSVSavedState

### ISSUE THREAD

**Issue by krisdev-pl** [claudiodegio/MsvSearch#15]
```
05-10 13:31:17.449 20384-20384/pl.krisdev.android.apps.hermes.school E/Parcel: Class not found when unmarshalling: com.claudiodegio.msv.BaseMaterialSearchView$BaseMSVSavedState
                                                                               java.lang.ClassNotFoundException: com.claudiodegio.msv.BaseMaterialSearchView$BaseMSVSavedState
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.Class.forName(Class.java:324)
                                                                                   at android.os.Parcel.readParcelableCreator(Parcel.java:2383)
                                                                                   at android.os.Parcel.readParcelable(Parcel.java:2337)
                                                                                   at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
                                                                                   at android.view.View$BaseSavedState.<init>(View.java:21614)
                                                                                   at android.view.View$BaseSavedState$1.createFromParcel(View.java:21636)
                                                                                   at android.view.View$BaseSavedState$1.createFromParcel(View.java:21634)
                                                                                   at android.os.Parcel.readParcelable(Parcel.java:2346)
                                                                                   at android.os.Parcel.readValue(Parcel.java:2243)
                                                                                   at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653)
                                                                                   at android.os.Parcel.readSparseArray(Parcel.java:1946)
                                                                                   at android.os.Parcel.readValue(Parcel.java:2300)
                                                                                   at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
                                                                                   at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                                   at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
                                                                                   at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2051)
                                                                                   at android.app.Activity.onRestoreInstanceState(Activity.java:1009)
                                                                                   at android.app.Activity.performRestoreInstanceState(Activity.java:964)
                                                                                   at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1164)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                                Caused by: java.lang.ClassNotFoundException: com.claudiodegio.msv.BaseMaterialSearchView$BaseMSVSavedState
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at java.lang.Class.classForName(Native Method) 
                                                                                   at java.lang.Class.forName(Class.java:324) 
                                                                                   at android.os.Parcel.readParcelableCreator(Parcel.java:2383) 
                                                                                   at android.os.Parcel.readParcelable(Parcel.java:2337) 
                                                                                   at android.view.AbsSavedState.<init>(AbsSavedState.java:57) 
                                                                                   at android.view.View$BaseSavedState.<init>(View.java:21614) 
                                                                                   at android.view.View$BaseSavedState$1.createFromParcel(View.java:21636) 
                                                                                   at android.view.View$BaseSavedState$1.createFromParcel(View.java:21634) 
                                                                                   at android.os.Parcel.readParcelable(Parcel.java:2346) 
                                                                                   at android.os.Parcel.readValue(Parcel.java:2243) 
                                                                                   at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653) 
                                                                                   at android.os.Parcel.readSparseArray(Parcel.java:1946) 
                                                                                   at android.os.Parcel.readValue(Parcel.java:2300) 
                                                                                   at android.os.Parcel.readArrayMapInternal(Parcel.java:2592) 
                                                                                   at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                                                                   at android.os.Bundle.getSparseParcelableArray(Bundle.java:856) 
                                                                                   at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2051) 
                                                                                   at android.app.Activity.onRestoreInstanceState(Activity.java:1009) 
                                                                                   at android.app.Activity.performRestoreInstanceState(Activity.java:964) 
                                                                                   at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1164) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                                                Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-10 13:31:17.452 20384-20384/pl.krisdev.android.apps.hermes.school D/AndroidRuntime: Shutting down VM
05-10 13:31:17.453 20384-20384/pl.krisdev.android.apps.hermes.school E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: pl.krisdev.android.apps.hermes.school, PID: 20384
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.krisdev.android.apps.hermes.school/pl.krisdev.android.apps.hermes.school.activities.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.claudiodegio.msv.BaseMaterialSearchView$BaseMSVSavedState
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                                        Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.claudiodegio.msv.BaseMaterialSearchView$BaseMSVSavedState
                                                                                           at android.os.Parcel.readParcelableCreator(Parcel.java:2411)
                                                                                           at android.os.Parcel.readParcelable(Parcel.java:2337)
                                                                                           at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
                                                                                           at android.view.View$BaseSavedState.<init>(View.java:21614)
                                                                                           at android.view.View$BaseSavedState$1.createFromParcel(View.java:21636)
                                                                                           at android.view.View$BaseSavedState$1.createFromParcel(View.java:21634)
                                                                                           at android.os.Parcel.readParcelable(Parcel.java:2346)
                                                                                           at android.os.Parcel.readValue(Parcel.java:2243)
                                                                                           at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653)
                                                                                           at android.os.Parcel.readSparseArray(Parcel.java:1946)
                                                                                           at android.os.Parcel.readValue(Parcel.java:2300)
                                                                                           at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
                                                                                           at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                                           at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
                                                                                           at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2051)
                                                                                           at android.app.Activity.onRestoreInstanceState(Activity.java:1009)
                                                                                           at android.app.Activity.performRestoreInstanceState(Activity.java:964)
                                                                                           at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1164)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
```

**Comment by kserno** [comment]
can you maybe more specify how did this happen ?

**Comment by om-nom** [comment]
It's happend because BaseMSVSavedState is not correct implement parcelable pattern. Check my PR for solution.
